using UnityEngine;

namespace Mabar.PhaserExporter.Editor
{
    public static class GameJsTemplate
    {
        public static string Generate(PhaserProjectSettings s)
        {
            string bgHex = ColorToHex(s.backgroundColor);

            return
$@"// {s.gameName}
// Generated by MABAR PhaserJS Exporter v0.1.0
// https://github.com/mabar-creativ/phaser-exporter

class BootScene extends Phaser.Scene {{
    constructor() {{
        super({{ key: 'BootScene' }});
    }}

    preload() {{
        // Load assets here
        // this.load.image('logo', 'assets/logo.png');
        // this.load.spritesheet('player', 'assets/player.png', {{ frameWidth: 32, frameHeight: 32 }});
    }}

    create() {{
        this.scene.start('GameScene');
    }}
}}

class GameScene extends Phaser.Scene {{
    constructor() {{
        super({{ key: 'GameScene' }});
    }}

    preload() {{
    }}

    create() {{
        const cx = {s.width} / 2;
        const cy = {s.height} / 2;

        this.add.text(cx, cy - 24, '{EscapeJs(s.gameName)}', {{
            fontSize: '38px',
            fontFamily: 'Arial, sans-serif',
            color: '#ffffff',
            fontStyle: 'bold'
        }}).setOrigin(0.5);

        this.add.text(cx, cy + 24, 'Built with MABAR PhaserJS Exporter', {{
            fontSize: '14px',
            fontFamily: 'Arial, sans-serif',
            color: '#888888'
        }}).setOrigin(0.5);
    }}

    update(time, delta) {{
        // Game loop — time: ms since start, delta: ms since last frame
    }}
}}

const config = {{
    type: Phaser.AUTO,
    width: {s.width},
    height: {s.height},
    backgroundColor: '#{bgHex}',
    scene: [BootScene, GameScene],
    scale: {{
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH
    }}
}};

const game = new Phaser.Game(config);
";
        }

        private static string ColorToHex(Color c)
        {
            int r = Mathf.RoundToInt(c.r * 255);
            int g = Mathf.RoundToInt(c.g * 255);
            int b = Mathf.RoundToInt(c.b * 255);
            return $"{r:X2}{g:X2}{b:X2}";
        }

        private static string EscapeJs(string s) =>
            s.Replace("\\", "\\\\").Replace("'", "\\'");
    }
}
